### ISSUE TITLE
create list, put in resources of tools that can be used to check out Aria

### ISSUE THREAD

**Issue by mkruijt** [HackYourFuture/HTML-CSS#24]

**Comment by ivanasetiawan** [comment]
**Manual checklist:**
https://a11yproject.com/checklist

**Automated accessibility testing**
[pa11y](https://www.npmjs.com/package/pa11y)

**Helpers**
[a11y outline](https://github.com/xi/a11y-outline/) - web extension to navigate page outlines easily
FF: [a11y outline](https://addons.mozilla.org/de/firefox/addon/a11y-outline/)
Chrome: [Accessibility for developer](https://chrome.google.com/webstore/detail/accessibility-developer-t/fpkknkljclfencbdbgkenhalefipecmb)

**Software**
Windows: [NVDA](https://www.nvaccess.org/)
Mac: [VoiceOver](https://www.apple.com/accessibility/mac/vision/)
