### ISSUE TITLE
Link doesn't work

### ISSUE THREAD

**Issue by acimanx** [HackYourFuture/HTML-CSS#31]
File [HTML-CSS/Week3/MAKEME.md](https://github.com/HackYourFuture/HTML-CSS/blob/master/Week3/MAKEME.md) have unexisting hyperlink.

`>[Here](https://github.com/HackYourFuture/JavaScript/blob/master/Week0/README.md) you find the readings you have to complete before your first JavaScript lecture`

#26 
Seems that it was fixed at the footer, but missed at the header.

**Comment by mkruijt** [comment]
Great thank you Andrew!
