### ISSUE TITLE
The CLI link in week3 readings, is not working.

### ISSUE THREAD

**Issue by mnvacym** [HackYourFuture/HTML-CSS#40]
Hello @NoerGitKat @unmeshvrije ,
When the CLI link is clicked it says "This is not the page that you are looking for." The link is here: https://github.com/HackYourFuture/CommandLine/blob/master/Lecture-2.md

**Comment by mnvacym** [comment]
I think maybe this has to be the link: https://github.com/HackYourFuture/CommandLine/blob/master/Week2/Lecture.md

**Comment by gijscor** [comment]
Fixed, thanks @ammarvehbi
