### ISSUE TITLE
Non-Working links in week 1&2 reading

### ISSUE THREAD

**Issue by anis790615** [HackYourFuture/HTML-CSS#53]
The links to articles on the website  intertnetingishard.com  do not work. The first link is in week 1 reading about semantic HTML: https://internetingishard.com/html-and-css/semantic-html/
The second is in week 2 reading about responsive design: https://internetingishard.com/html-and-css/responsive-design/).

**Comment by NoerGitKat** [comment]
@anis790615 Can you check again? When I click those links it seems to work just fine.

**Comment by anis790615** [comment]
@NoerGitKat They do work now. Perhaps it was a temporary issue on their website. Thanks
