### ISSUE TITLE
The screenshot for 1.GitHub homework guide

### ISSUE THREAD

**Issue by atabek-furkad** [HackYourFuture/HTML-CSS#67]
Hello,

This link https://github.com/HackYourFuture/HTML-CSS/blob/master/hand-in-homework-guide.md seems to have an outdated screenshot, though I may be wrong. 
When I open settings of the repository I don't find what the screenshot displays, instead I see this 
![image](https://user-images.githubusercontent.com/71214731/96144004-fb473b00-0f03-11eb-8ba6-d2c7a54e5bd4.png)
I don't think it is a big deal, but for beginners like me, some things are not obvious sometimes. So, I suppose it would be nice to replace it.

With respect,
Atabek

**Comment by fadialset** [comment]
It is the same happening with me
