### ISSUE TITLE
GIT is easier to learn without the CLI

### ISSUE THREAD

**Issue by tomasvanrijsse** [HackYourFuture/HTML-CSS#86]
Most people I know don't use GIT on the command line.
And I think that using a visual representation works better didactically.
I'd would argue that it makes more sense to start talking about the CLI once the students start to work with NPM.

[Gitkraken](https://www.gitkraken.com/) is the GIT client I would advise because:
1. It is free
2. It is available on all platforms
3. It has a nice [graph view](https://1v5ymx3zt3y73fq5gy23rtnc-wpengine.netdna-ssl.com/wp-content/uploads/2021/05/gk-product-3.png) of the commits ( you can easily demonstrate branches and merging ) 
4. They have a lot of [tutorials ](https://www.gitkraken.com/learn/git/tutorials) that are pretty good.

**Comment by tomasvanrijsse** [comment]
> Tip: make use of the CLI to practice your GIT skills. This not only teaches you how GIT works, but also how to work like a real software developer!

(copied from week 3 makeme.md)

I'm really annoyed when I see quotes like these :man_facepalming: 
IMHO using the CLI doesn't make you a 'real software developer', this is just a strong opinion from the person who wrote this course.

**Comment by robvk** [comment]
I always use the CLI for git, but agree with you that our curriculum should be neutral on these kinds of things. In the homework for JavaScript the students already need to do some npm things to set up so definitely need to keep CLI basics in this module.

Will see if I can make a PR in the upcoming week to add GUI's to the options for git and give students the choice what to do.

**Comment by robvk** [comment]
Finally got round to it and that line is gone plus I have linked to gitkraken and vscode extension as an alternative. No more lies about being real software developers. Thanks, as always, for suggestions to making the curriculum better
