### ISSUE TITLE
The Live HTML previewer doesn't seem to work any longer

### ISSUE THREAD

**Issue by johanf85** [HackYourFuture/HTML-CSS#92]
In Week0's [README.md](https://github.com/HackYourFuture/HTML-CSS/blob/master/Week0/README.md) a link is provided to [Live HTML Previewer](https://marketplace.visualstudio.com/items?itemName=hdg.live-html-previewer). However I couldn't get it to work. Looking at the [reviews](https://marketplace.visualstudio.com/items?itemName=hdg.live-html-previewer&ssr=false#review-details) on the Marketplace, a lot of people are experiencing the same. It doesn't seem to work any longer.

**Comment by robvk** [comment]
Thanks for the heads up @johanf85! I have removed it from the list now, don't think we need to go with an alternative.

**Comment by johanf85** [comment]
Allright, I tried looking for some alternatives too, but AFAIK there is no live previewer available, only Previewers that need to be executed by a command to see a preview. But anyone can decide to find and use these themselves if they want of course. 👍🏻
